// Generated by CoffeeScript 1.7.1
(function() {
  var config, reqwest;

  config = require('../shared/config');

  reqwest = require('reqwest');

  module.exports = function() {
    var endpoint, error, mapping, pendingRequests, postData, prefix, send, sendingRequests, success;
    prefix = config.api;
    pendingRequests = {};
    sendingRequests = {};
    mapping = {
      id: "user_id",
      p: "site_page_vw",
      a: "site_ad_req",
      av: "site_ad_vw",
      ac: "site_ad_clk",
      ae: "site_ad_vw_eng",
      v: "site_vis",
      vp: "vis_page_vw",
      va: "vis_ad_req",
      vav: "vis_ad_vw",
      vae: "vis_ad_vw_eng",
      vac: "vis_ad_clk"
    };
    send = function(obj) {
      pendingRequests[obj.id] = obj;
      return postData();
    };
    success = function(obj, cb) {};
    error = function(obj, cb) {};
    postData = function() {
      var id, k, obj, params, v, _ref, _results;
      _results = [];
      for (id in pendingRequests) {
        obj = pendingRequests[id];
        if (!(!sendingRequests[obj.id])) {
          continue;
        }
        delete pendingRequests[id];
        params = {};
        _ref = obj.attributes;
        for (k in _ref) {
          v = _ref[k];
          params[mapping[k] || k] = v;
        }
        _results.push(send(prefix + obj.path, params));
      }
      return _results;
    };
    endpoint = {
      send: send
    };
    if (process.env.ENV === "test") {
      return endpoint.postData = postData;
    }
  };

}).call(this);
