// Generated by CoffeeScript 1.7.1
(function() {
  var config, utils;

  config = require('../shared/config');

  utils = require('../shared/utils');

  module.exports = (function($sf) {
    var RETRY_TIMEOUT, endpoint, error, isTimeout, pendingRequests, postData, prefix, send, sendData, sendingRequests, success, timeoutValue;
    prefix = config.api;
    pendingRequests = {};
    sendingRequests = {};
    RETRY_TIMEOUT = 100;
    isTimeout = false;
    timeoutValue = null;
    send = function(obj, options, cb) {
      pendingRequests[obj.id] = [obj, cb];
      return postData(options);
    };
    success = function(obj, resp, cb) {
      obj.set(resp, {
        silent: true
      });
      delete sendingRequests[obj.id];
      return typeof cb === "function" ? cb(obj) : void 0;
    };
    error = function(obj, err, cb) {};
    sendData = function(params, obj, cb) {
      var requestParams;
      requestParams = {
        data: params,
        success: function(resp) {
          return success(obj, resp, cb);
        },
        error: function(err) {
          return error(obj, err, cb);
        }
      };
      if (prefix.indexOf(document.location.hostname) >= 0) {
        requestParams.method = "post";
        requestParams.url = obj.path;
      } else {
        requestParams.type = "jsonp";
        requestParams.url = prefix + obj.path;
      }
      return utils.sendRequest(requestParams);
    };
    postData = function() {
      var cb, id, k, obj, params, v, _ref, _ref1;
      for (id in pendingRequests) {
        _ref = pendingRequests[id], obj = _ref[0], cb = _ref[1];
        if (!sendingRequests[obj.id]) {
          delete pendingRequests[id];
          params = {};
          _ref1 = obj.changedFields();
          for (k in _ref1) {
            v = _ref1[k];
            params[k] = v;
          }
          sendingRequests[obj.id] = obj;
          sendData(params, obj, cb);
        }
      }
      if ($sf.lib.lang.keys(pendingRequests).length > 0 && !isTimeout) {
        isTimeout = true;
        return timeoutValue = setTimeout(function() {
          isTimeout = false;
          return postData();
        }, RETRY_TIMEOUT);
      }
    };
    endpoint = {
      send: send
    };
    if (process.env.ENV === "test") {
      endpoint.postData = postData;
      endpoint.sendData = sendData;
      endpoint.success = success;
      endpoint.error = error;
      endpoint.sendingRequests = sendingRequests;
      endpoint.pendingRequests = pendingRequests;
      endpoint.clear = function() {
        isTimeout = false;
        sendingRequests = {};
        pendingRequests = {};
        endpoint.sendingRequests = sendingRequests;
        endpoint.pendingRequests = pendingRequests;
        return clearTimeout(timeoutValue);
      };
    }
    return endpoint;
  })($sf);

}).call(this);
