// Generated by CoffeeScript 1.7.1
(function() {
  var config, stream;

  config = require('../shared/config');

  stream = require('../shared/stream');

  module.exports = function(AdJS, request, window) {
    request.change(function() {
      return stream.event(request);
    });
    request.set({
      load_pos: utils.getFramePosition(window),
      v_js: config.version,
      req_url_blind: true,
      tz: (new Date()).getTimezoneOffset()
    });
    AdJS.load(function() {
      return request.set({
        load_chain: AdJS.loadChain
      });
    });
    AdJS.request(function() {
      var geoInfo, _base;
      AdJS.requestTime = utils.now();
      geoInfo = $sf.ext.geom();
      return request.set({
        requested: true,
        requestedAt: utils.now(),
        req_t: utils.now() - startTicks,
        req_view_pct: typeof (_base = $sf.ext).inViewPercentage === "function" ? _base.inViewPercentage() : void 0,
        slot_x: geoInfo.self.l,
        slot_y: geoInfo.self.t,
        slot_w: geoInfo.self.w,
        slot_h: geoInfo.self.h,
        screen_w: window.screen.width,
        screen_h: window.screen.height,
        vp_x: geoInfo.win.l,
        vp_y: geoInfo.win.t,
        vp_w: geoInfo.win.w,
        vp_h: geoInfo.win.h
      });
    });
    AdJS.load(function() {
      AdJS.loadTime = utils.now();
      sfDom.attach(window, "unload", function() {
        return $ad.unload();
      });
      return request.set({
        loaded: true,
        loadedAt: utils.now(),
        load_t: utils.now() - startTicks
      });
    });
    AdJS.view(function() {
      AdJS.viewTime = utils.now();
      return request.set({
        viewed: true,
        viewedAt: utils.now(),
        view_t: utils.now() - startTicks,
        view_meas: true,
        view_pct: utils.reduce(viewedPercentages, (function(memo, num) {
          return memo + num;
        }), 0) / viewedPercentages.length,
        view_pct_max: maxViewPercentage
      });
    });
    AdJS.engage(function() {
      AdJS.engageTime = utils.now();
      return request.set({
        engaged: true,
        view_eng: true,
        engagedAt: utils.now()
      });
    });
    AdJS.click(function() {
      AdJS.clickTime = utils.now();
      return request.set({
        clicked: true,
        clickedAt: utils.now(),
        clk_t: utils.now() - startTicks
      });
    });
    AdJS.unview(function() {
      return request.set({
        unviewed: true,
        unviewedAt: utils.now(),
        view_dur: utils.now() - AdJS.viewedAt,
        view_pct_max: maxViewPercentage
      });
    });
    return AdJS.unload(function() {
      AdJS.unloadTime = utils.now();
      return request.set({
        unloaded: true,
        unloadedAt: utils.now(),
        unl_t: utils.now() - startTicks
      });
    });
  };

}).call(this);
