// Generated by CoffeeScript 1.7.1

/*
  this should handle everything but
 */

(function() {
  var events;

  events = require('./shared/event')(["request", "load", "view", "click", "expanded", "collapsed", "engage", "unview", "unload"]);

  module.exports = (function($sf, window) {
    var Slot;
    Slot = (function() {
      function Slot() {}

      return Slot;

    })();
    return new Slot();
  })($sf, window);

}).call(this);
