// Generated by CoffeeScript 1.7.1
(function() {
  var Base,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require('./base');

  module.exports = (function(window) {
    var AdRequest;
    AdRequest = (function(_super) {
      __extends(AdRequest, _super);

      function AdRequest(serializedParams) {
        AdRequest.__super__.constructor.apply(this, arguments);
        if (serializedParams) {
          this.deserialize(serializedParams);
        } else {
          this.set({
            full_url: window.document.location.href,
            referrer: window.document.referrer
          }, {
            silent: true
          });
        }
      }

      AdRequest.prototype.path = "/ad";

      AdRequest.prototype.constantFields = ["site_user_id", "page_id", "visit_id", "ad_id"];

      return AdRequest;

    })(Base);
    return AdRequest;
  })(window);

}).call(this);
