// Generated by CoffeeScript 1.7.1
(function() {
  var Base, config,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require('./base');

  config = require('./config');

  module.exports = (function(window) {
    var AdRequest;
    AdRequest = (function(_super) {
      __extends(AdRequest, _super);

      function AdRequest(serializedParams) {
        AdRequest.__super__.constructor.apply(this, arguments);
        if (serializedParams) {
          this.deserialize(serializedParams);
        } else {
          this.set({
            url: window.document.location.href,
            ref: window.document.referrer,
            v_js: config.version
          }, {
            silent: true
          });
        }
      }

      AdRequest.prototype.serializedAttributes = function() {
        var k, outAttrs, v, _ref;
        outAttrs = {};
        _ref = this.attributes;
        for (k in _ref) {
          v = _ref[k];
          outAttrs[k] = v;
        }
        outAttrs.url = encodeURIComponent(outAttrs.url);
        outAttrs.ref = encodeURIComponent(outAttrs.ref);
        return outAttrs;
      };

      AdRequest.prototype.deserialize = function(params) {
        AdRequest.__super__.deserialize.call(this, params);
        return this.set({
          url: decodeURIComponent(this.attributes.url),
          ref: decodeURIComponent(this.attributes.ref)
        }, {
          silent: true
        });
      };

      AdRequest.prototype.path = "/ad";

      AdRequest.prototype.constantFields = ["site_user_id", "page_id", "visit_id", "ad_id"];

      return AdRequest;

    })(Base);
    return AdRequest;
  })(window);

}).call(this);
