// Generated by CoffeeScript 1.7.1
(function() {
  var endpoint, utils;

  endpoint = require('./endpoint');

  utils = require('./utils');

  module.exports = (function(window) {
    var work;
    work = function(adRequest, pubFrame) {
      var controller;
      controller = null;
      utils.defineProperty(window, "getDetails", {
        writeable: false,
        value: function() {
          return adRequest;
        },
        configurable: false
      });
      return endpoint.send(adRequest, function() {
        if (pubFrame) {
          pubFrame.$ad.readAd(window);
          return utils.findController(function(ctrl) {
            controller = ctrl;
            return adRequest.change(function() {
              return controller.send(adRequest);
            });
          });
        }
      });
    };
    return {
      work: work
    };
  })(window);

}).call(this);
