// Generated by CoffeeScript 1.7.1
(function() {
  var utils, uuid;

  uuid = require('node-uuid');

  utils = require('./utils');

  module.exports = (function() {
    var Base;
    return Base = (function() {
      function Base() {
        this.id = uuid.v4();
        this.attributes || (this.attributes = {});
        this._events = [];
        this._dirty = {};
      }

      Base.prototype.set = function(attrs, options) {
        var changed, changedAttributes, f, k, v, _i, _len, _ref, _results;
        if (options == null) {
          options = {};
        }
        if (typeof attrs !== "object") {
          throw "attrs must be an object";
        }
        changed = false;
        changedAttributes = [];
        for (k in attrs) {
          v = attrs[k];
          if (this.attributes[k] !== v) {
            changedAttributes.push(k);
            this._dirty[k] = v;
            this.attributes[k] = v;
          }
        }
        if (!options.silent && changedAttributes.length > 0) {
          _ref = this._events;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            f = _ref[_i];
            _results.push(f.apply(this, [this, changedAttributes]));
          }
          return _results;
        }
      };

      Base.prototype.change = function(f) {
        var _i, _len, _ref, _results;
        if (f && typeof f === "function") {
          return this._events.push(f);
        } else if (!f) {
          _ref = this._events;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            f = _ref[_i];
            _results.push(f.apply(this, arguments));
          }
          return _results;
        }
      };

      Base.prototype._cleanDirty = function() {
        return this._dirty = {};
      };

      Base.prototype.changedFields = function() {
        var field, k, params, v, _i, _len, _ref, _ref1;
        params = {};
        _ref = this._dirty;
        for (k in _ref) {
          v = _ref[k];
          params[k] = v;
        }
        _ref1 = this.constantFields;
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          field = _ref1[_i];
          if (this.attributes[field]) {
            params[field] = this.attributes[field];
          }
        }
        this._cleanDirty();
        return params;
      };

      Base.prototype.serialize = function() {
        return utils.toQuery(this.attributes);
      };

      Base.prototype.deserialize = function(str) {
        return this.set(utils.fromQuery(str), {
          silent: true
        });
      };

      return Base;

    })();
  })();

}).call(this);
