// Generated by CoffeeScript 1.7.1
(function() {
  var config, utils;

  config = require('./config');

  utils = require('./utils');

  module.exports = (function($sf) {
    var RETRY_TIMEOUT, combine, endpoint, error, isTimeout, pendingRequests, postData, prefix, send, sendData, sendingRequests, success, timeoutValue;
    prefix = config.api;
    pendingRequests = {};
    sendingRequests = {};
    RETRY_TIMEOUT = 100;
    isTimeout = false;
    timeoutValue = null;
    send = function(obj, cb) {
      pendingRequests[obj.id] = [obj, cb];
      return postData();
    };
    combine = function(req, adReq, cb, retry) {
      var attrs, f, requestParams, _i, _j, _len, _len1, _ref, _ref1;
      if (retry == null) {
        retry = 3;
      }
      attrs = {};
      if (req.attributes.req_id && adReq.attributes.ad_id) {
        _ref = adReq.constantFields;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          f = _ref[_i];
          attrs[f] = adReq.attributes[f];
        }
        _ref1 = req.constantFields;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          f = _ref1[_j];
          attrs[f] = req.attributes[f];
        }
        requestParams = {
          data: attrs,
          success: function(resp) {
            return typeof cb === "function" ? cb(resp) : void 0;
          },
          error: function(err) {
            return typeof cb === "function" ? cb(err) : void 0;
          }
        };
        if (prefix.indexOf(document.location.hostname) >= 0) {
          requestParams.method = "post";
          requestParams.url = "event_ads";
        } else {
          requestParams.type = "jsonp";
          requestParams.url = prefix + "/event_ads";
        }
        return utils.sendRequest(requestParams);
      } else if (retry >= 0) {
        return setTimeout(((function(_this) {
          return function() {
            return combine(req, adReq, cb, retry - 1);
          };
        })(this)), 100);
      }
    };
    success = function(obj, resp, cb) {
      obj.set(resp, {
        silent: true
      });
      delete sendingRequests[obj.id];
      console.log("cb");
      return typeof cb === "function" ? cb(obj) : void 0;
    };
    error = function(obj, err, cb) {};
    sendData = function(params, obj, cb) {
      var requestParams;
      requestParams = {
        data: params,
        success: function(resp) {
          return success(obj, resp, cb);
        },
        error: function(err) {
          return error(obj, err, cb);
        }
      };
      if (prefix.indexOf(document.location.hostname) >= 0) {
        requestParams.method = "post";
        requestParams.url = obj.path;
      } else {
        requestParams.type = "jsonp";
        requestParams.url = prefix + obj.path;
      }
      return utils.sendRequest(requestParams);
    };
    postData = function() {
      var cb, id, k, obj, params, v, _ref, _ref1;
      for (id in pendingRequests) {
        _ref = pendingRequests[id], obj = _ref[0], cb = _ref[1];
        if (!sendingRequests[obj.id]) {
          delete pendingRequests[id];
          params = {};
          _ref1 = obj.changedFields();
          for (k in _ref1) {
            v = _ref1[k];
            params[k] = v;
          }
          sendingRequests[obj.id] = obj;
          sendData(params, obj, cb);
        }
      }
      if ($sf.lib.lang.keys(pendingRequests).length > 0 && !isTimeout) {
        isTimeout = true;
        return timeoutValue = setTimeout(function() {
          isTimeout = false;
          return postData();
        }, RETRY_TIMEOUT);
      }
    };
    endpoint = {
      send: send,
      combine: combine
    };
    if (process.env.ENV === "test") {
      endpoint.postData = postData;
      endpoint.sendData = sendData;
      endpoint.success = success;
      endpoint.error = error;
      endpoint.sendingRequests = sendingRequests;
      endpoint.pendingRequests = pendingRequests;
      endpoint.clear = function() {
        isTimeout = false;
        sendingRequests = {};
        pendingRequests = {};
        endpoint.sendingRequests = sendingRequests;
        endpoint.pendingRequests = pendingRequests;
        return clearTimeout(timeoutValue);
      };
    }
    return endpoint;
  })($sf);

}).call(this);
