// Generated by CoffeeScript 1.7.1
(function() {
  var utils;

  utils = require('./utils');

  module.exports = (function(window, $sf) {
    var ENGAGEMENT_RESET, activityHandler, attach, disengageEvents, doc, engageEvents, engagement, engagementTimeout, lastEngaged, resetEngagement;
    attach = $sf.lib.dom.attach;
    engagement = {
      isEngaged: false
    };
    doc = window.document;
    engageEvents = [];
    disengageEvents = [];
    ENGAGEMENT_RESET = 3000;
    lastEngaged = void 0;
    engagement.onEngagement = function(f) {
      return engageEvents.push(f);
    };
    engagement.onDisengagement = function(f) {
      return disengageEvents.push(f);
    };
    activityHandler = function() {
      var f, _i, _len;
      engagement.isEngaged = true;
      engagement.lastEngaged = utils.now();
      for (_i = 0, _len = engageEvents.length; _i < _len; _i++) {
        f = engageEvents[_i];
        f();
      }
      resetEngagement();
      return true;
    };
    engagementTimeout = null;
    resetEngagement = function() {
      clearTimeout(engagementTimeout);
      return engagementTimeout = setTimeout(function() {
        var f, _i, _len;
        engagement.isEngaged = false;
        for (_i = 0, _len = disengageEvents.length; _i < _len; _i++) {
          f = disengageEvents[_i];
          f();
        }
        return disengageEvents = [];
      }, ENGAGEMENT_RESET);
    };
    attach(doc, 'click', activityHandler);
    attach(doc, 'mouseup', activityHandler);
    attach(doc, 'mousedown', activityHandler);
    attach(doc, 'mousemove', activityHandler);
    attach(doc, 'mousewheel', activityHandler);
    attach(doc, 'keypress', activityHandler);
    attach(doc, 'keydown', activityHandler);
    attach(doc, 'keyup', activityHandler);
    attach(window, 'DOMMouseScroll', activityHandler);
    attach(window, 'scroll', activityHandler);
    attach(window, 'resize', activityHandler);
    attach(window, 'focus', activityHandler);
    attach(window, 'blur', activityHandler);
    return engagement;
  })(window, $sf);

}).call(this);
