// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(eventNames) {
    return (function() {
      var event, events, utils, _i, _len;
      utils = require('./utils');
      events = {
        on: function(event, cb) {
          var eventList;
          this.events || (this.events = {});
          eventList = this.events[event] || [];
          eventList.push(cb);
          this.events[event] = eventList;
          return this;
        },

        /*
          optionalData needs to be fixed
         */
        trigger: function(event, data, optionalData) {
          var e, ex, _i, _len, _ref;
          this.events || (this.events = {});
          _ref = this.events[event] || [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            e = _ref[_i];
            try {
              e.call(this, data, optionalData);
            } catch (_error) {
              ex = _error;
            }
          }
          this.notify(event, data || this);
          return this;
        },
        notify: function(event, data) {
          var endpoint, params, _i, _len, _ref, _ref1, _results;
          _ref1 = ((_ref = this.eventEndpoints) != null ? _ref[event] : void 0) || [];
          _results = [];
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            endpoint = _ref1[_i];
            params = (data != null ? typeof data.getParams === "function" ? data.getParams() : void 0 : void 0) || {};
            params.event = event;
            _results.push(utils.sendRequest(endpoint, {
              data: params
            }));
          }
          return _results;
        }
      };
      for (_i = 0, _len = eventNames.length; _i < _len; _i++) {
        event = eventNames[_i];
        events[event] = (function(event) {
          var f;
          return f = function(data) {
            if (typeof data === "function") {
              return this.on(event, data);
            } else {
              return this.trigger(event, data);
            }
          };
        })(event);
        events["" + event + "RegisterEndpoint"] = (function(event) {
          var f;
          return f = function(endpoint) {
            var _base;
            this.eventEndpoints || (this.eventEndpoints = {});
            (_base = this.eventEndpoints)[event] || (_base[event] = []);
            return this.eventEndpoints[event].push(endpoint);
          };
        })(event);
      }
      return events;
    })();
  };

}).call(this);
