// Generated by CoffeeScript 1.7.1
(function() {
  (function() {
    var Field, sendOnce;
    sendOnce = ["viewed", "loaded", "clicked", "unload"];
    return Field = (function() {
      function Field(fieldNm, value) {
        this.fieldNm = fieldNm;
        this.value = value;
      }

      Field.prototype.serialize = function() {
        if (this.serialized) {
          return {};
        }
        if (sendOnce.indexOf(this.fieldName) > -1) {
          return this.serialized = true;
        }
      };

      return Field;

    })();
  })();

}).call(this);
