// Generated by CoffeeScript 1.7.1
(function() {
  var Base, config, cookies, moment, utils, uuid,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  cookies = require('cookies-js');

  uuid = require('node-uuid');

  Base = require('./base');

  utils = require('./utils');

  config = require('./config');

  moment = require('moment');

  module.exports = (function($sf, window) {
    var COOKIE_KEY, Page;
    COOKIE_KEY = "_ajsk";
    Page = (function(_super) {
      __extends(Page, _super);

      function Page(serializedParams) {
        Page.__super__.constructor.call(this);
        if (serializedParams) {
          this.deserialize(serializedParams);
        } else {
          this.loadCookieData();
          this.initDefaultAttributes();
        }
      }

      Page.prototype.storeCookie = function() {
        var _ref;
        if (($sf != null ? (_ref = $sf.ext) != null ? _ref.cookie : void 0 : void 0) != null) {
          if (this.attributes.site_user_id) {
            $sf.ext.cookie("" + COOKIE_KEY + "_suid", {
              value: this.attributes.site_user_id,
              expires: moment().add("years", 1).toDate()
            });
          }
          if (this.attributes.visit_id) {
            return $sf.ext.cookie("" + COOKIE_KEY + "_vid", {
              value: this.attributes.visit_id,
              expires: moment().add("years", 1).toDate()
            });
          }
        } else {
          if (this.attributes.site_user_id) {
            cookies.set("" + COOKIE_KEY + "_suid", this.attributes.site_user_id, {
              expires: moment().add("minutes", config.visit_expiry).toDate()
            });
          }
          if (this.attributes.visit_id) {
            return cookies.set("" + COOKIE_KEY + "_vid", this.attributes.visit_id, {
              expires: moment().add("minutes", config.visit_expiry).toDate()
            });
          }
        }
      };

      Page.prototype.loadCookieData = function() {
        var _ref;
        if (($sf != null ? (_ref = $sf.ext) != null ? _ref.cookie : void 0 : void 0) != null) {
          return this.set({
            site_user_id: $sf.ext.cookie("" + COOKIE_KEY + "_suid"),
            visit_id: $sf.ext.cookie("" + COOKIE_KEY + "_vid")
          }, {
            silent: true
          });
        } else {
          return this.set({
            site_user_id: cookies.get("" + COOKIE_KEY + "_suid"),
            visit_id: cookies.get("" + COOKIE_KEY + "_vid")
          }, {
            silent: true
          });
        }
      };

      Page.prototype.set = function(attrs, options) {
        if (options == null) {
          options = {};
        }
        Page.__super__.set.call(this, attrs, options);
        return this.storeCookie();
      };

      Page.prototype.initDefaultAttributes = function() {
        if (window === window.top) {
          return this.set({
            full_url: window.document.location.href,
            referrer: window.document.referrer
          }, {
            silent: true
          });
        } else if (window.parent === window.top) {
          return this.set({
            full_url: window.document.referrer
          });
        }
      };

      Page.prototype.verifyUrl = function() {
        if (window.parent === window.top && window.document.referrer) {
          return true;
        }
      };

      Page.prototype.path = "/page";

      Page.prototype.constantFields = ["site_user_id", "page_id", "visit_id", "full_url"];

      return Page;

    })(Base);
    Page.VISITOR_EXPIRY = config.visit_expiry;
    if (process.env.ENV === "test" || ((typeof _TEST !== "undefined" && _TEST !== null) && _TEST)) {
      Page._updateVisitId = updateVisitId;
      Page._parseCookie = parseCookie;
      Page._getUser = getUserId;
      Page._COOKIE_KEY = COOKIE_KEY;
      Page.clearCookie = function() {
        cookies.set(COOKIE_KEY + "_suid", void 0);
        return cookies.set(COOKIE_KEY + "_vid", void 0);
      };
    }
    return Page;
  })($sf, window);

}).call(this);
