// Generated by CoffeeScript 1.7.1
(function() {
  var Base, cookies, utils, uuid,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  cookies = require('cookies-js');

  uuid = require('node-uuid');

  Base = require('./base');

  utils = require('./utils');

  module.exports = (function() {
    var COOKIE_KEY, Session, defaultAttributes, getUserId, now, parseCookie, updateVisitId;
    COOKIE_KEY = "_ajsk";
    now = utils.now();
    updateVisitId = function(options) {
      var nowTime;
      nowTime = utils.now() / 1000;
      this.lastVisitTime || (this.lastVisitTime = utils.toNumber(this.attributes.vts, 0));
      if ((nowTime - Session.VISITOR_EXPIRY) > this.lastVisitTime) {
        return this.set({
          v: utils.toNumber(this.attributes.v) + 1,
          vts0: this.attributes.vts,
          vts: nowTime,
          vid: uuid.v4(),
          vp: 0,
          va: 0,
          vav: 0,
          vae: 0,
          vac: 0
        }, options);
      } else {
        this.lastVisitTime = nowTime;
        return this.set({
          vts: nowTime
        }, {
          silent: true
        });
      }
    };
    parseCookie = function(cookie) {
      return utils.fromQuery(cookie);
    };
    getUserId = function() {
      return utils.sendRequest();
    };
    defaultAttributes = function() {
      return {
        id: uuid.v4(),
        vid: uuid.v4(),
        ts: now / 1000,
        p: 0,
        a: 0,
        av: 0,
        ac: 0,
        ae: 0,
        v: 1,
        vts: now / 1000,
        vts0: now / 1000,
        vp: 0,
        va: 0,
        vav: 0,
        vae: 0,
        vac: 0
      };
    };
    Session = (function(_super) {
      __extends(Session, _super);

      function Session(query) {
        var attrs, cookie, k, v, _base, _ref;
        Session.__super__.constructor.call(this);
        _ref = defaultAttributes();
        for (k in _ref) {
          v = _ref[k];
          (_base = this.attributes)[k] || (_base[k] = v);
        }
        if (query) {
          attrs = parseCookie(query);
          this.set(attrs, {
            silent: true
          });
        } else if (cookie = cookies.get(COOKIE_KEY)) {
          attrs = parseCookie(cookie);
          this.set(attrs, {
            silent: true
          });
          updateVisitId.call(this, {
            silent: true
          });
          this.serializeCookie();
        } else {
          this.serializeCookie();
        }
      }

      Session.prototype.serializeCookie = function() {
        var query;
        query = utils.toQuery(this.attributes);
        cookies.set(COOKIE_KEY, query, {
          expires: 31536000
        });
        return query;
      };

      Session.prototype.set = function(attrs, options) {
        if (options == null) {
          options = {};
        }
        Session.__super__.set.call(this, attrs, options);
        return this.serializeCookie();
      };

      Session.prototype.incr = function(key, options) {
        var updatedVals, vkey, _base;
        (_base = this.attributes)[key] || (_base[key] = 0);
        updatedVals = {};
        updatedVals[key] = utils.toNumber(this.attributes[key]) + 1;
        vkey = "v" + key;
        if (this.attributes[vkey] != null) {
          updatedVals[vkey] = utils.toNumber(this.attributes[vkey]) + 1;
        }
        return this.set(updatedVals, options);
      };

      return Session;

    })(Base);
    Session.VISITOR_EXPIRY = 20;
    if ((typeof _TEST !== "undefined" && _TEST !== null) && _TEST) {
      Session._updateVisitId = updateVisitId;
      Session._parseCookie = parseCookie;
      Session._getUser = getUserId;
      Session._COOKIE_KEY = COOKIE_KEY;
      Session.clearCookie = function() {
        return cookies.set(COOKIE_KEY, void 0);
      };
    }
    return Session;
  })();

}).call(this);
