// Generated by CoffeeScript 1.7.1
(function() {
  var config, reqwest;

  reqwest = require('reqwest');

  config = require('./config');

  module.exports = (function() {
    var mapping, pendingRequests, prefix, send, sendingRequests;
    prefix = config.api;
    pendingRequests = {};
    sendingRequests = {};
    mapping = {
      id: "user_id",
      p: "site_page_vw",
      a: "site_ad_req",
      av: "site_ad_vw",
      ac: "site_ad_clk",
      ae: "site_ad_vw_eng",
      v: "site_vis",
      vp: "vis_page_vw",
      va: "vis_ad_req",
      vav: "vis_ad_vw",
      vae: "vis_ad_vw_eng",
      vac: "vis_ad_clk"
    };
    send = function(url, data, success, error) {
      return reqwest({
        url: url,
        type: 'jsonp',
        data: data,
        success: success,
        error: error
      });
    };
    return {
      page: function(session) {
        var error, success;
        success = function(resp) {
          return session.set(resp);
        };
        error = function(err) {
          return console.log("ERROR:" + err);
        };
        return send(prefix + '/page', session.attributes, success, error);
      },
      event: function(request, cb, isAttempt) {
        var error, k, params, success, v, _ref;
        success = function(resp) {
          request.set(resp, {
            silent: true
          });
          if (typeof cb === "function") {
            cb(resp);
          }
          return delete sendingRequests[request.id];
        };
        error = function(err) {
          return console.log("ERROR:" + err);
        };
        if (!sendingRequests[request.id]) {
          delete pendingRequests[request.id];
          sendingRequests[request.id] = true;
          params = {};
          _ref = request.attributes;
          for (k in _ref) {
            v = _ref[k];
            params[mapping[k] || k] = v;
          }
          return send(prefix + '/event', params, success, error);
        } else if (!pendingRequests[request.id] || isAttempt) {
          pendingRequests[request.id];
          return setTimeout((function(_this) {
            return function() {
              return _this.event(request, cb, true);
            };
          })(this), 500);
        }
      }
    };
  })();

}).call(this);
