// Generated by CoffeeScript 1.7.1
(function() {
  var capitalizeString;

  window.reqwest || (window.reqwest = require('reqwest'));

  window.JSON || (window.JSON = require('json'));

  module.exports = (function($sf, window) {
    var countFrames, defineProperty, e, e2, fromQuery, getReferrer, now, referrer, reqwest, sendRequest, toNumber, toQuery;
    reqwest = window.reqwest;
    sendRequest = function(url, options) {
      return reqwest({
        url: url,
        type: 'jsonp',
        success: options.success,
        error: options.error,
        data: options.data
      });
    };
    fromQuery = function(query, delim) {
      var item, key, params, value, _i, _len, _ref, _ref1;
      if (query == null) {
        query = "";
      }
      if (delim == null) {
        delim = "&";
      }
      params = {};
      _ref = query.split(delim);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        _ref1 = item.split("="), key = _ref1[0], value = _ref1[1];
        params[key] = decodeURIComponent(value);
      }
      return params;
    };
    toQuery = function(attributes) {
      return reqwest.toQueryString(attributes);
    };
    toNumber = function(val) {
      return $sf != null ? $sf.lib.lang.cnum(val, 0) : void 0;
    };
    now = function() {
      return (new Date()).getTime();
    };
    defineProperty = function(obj, prop, descriptor) {
      var e;
      try {
        if ("defineProperty" in Object) {
          return Object.defineProperty(obj, prop, descriptor);
        } else if ("__defineGetter__" in obj) {
          if (descriptor.value) {
            obj.__defineGetter__(prop, function() {
              return descriptor.value;
            });
            if (descriptor.writable !== false) {
              return obj.__defineSetter__(prop, function(val) {
                return val[prop] = val;
              });
            }
          } else {
            if (descriptor.get != null) {
              obj.__defineGetter__(prop, descriptor.get);
            }
            if (descriptor.set != null) {
              return obj.__defineSetter__(prop, descriptor.set);
            }
          }
        }
      } catch (_error) {
        e = _error;
        return console.log(e);
      }
    };
    countFrames = function(win) {
      var count, frame, _i, _len, _ref;
      count = win.frames.length;
      _ref = win.frames;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        frame = _ref[_i];
        if (frame !== win) {
          count += countFrames(frame);
        }
      }
      return count;
    };
    getReferrer = function(win) {
      var qs, referrer;
      referrer = '';
      qs = object.fromQuerystring("referrer", window.location.href) || object.fromQuerystring("referer", window.location.href);
      if (qs) {
        return qs;
      }
    };
    try {
      referrer = window.top.document.referrer;
    } catch (_error) {
      e = _error;
      if (window.parent) {
        try {
          referrer = window.parent.document.referrer;
        } catch (_error) {
          e2 = _error;
          referrer = "";
        }
      }
    }
    if (referrer === "") {
      referrer = document.referrer;
    }
    return referrer;
  })($sf, window);

  object.addEventListener = function(element, eventType, eventHandler, useCapture) {
    if (element.addEventListener) {
      element.addEventListener(eventType, eventHandler, useCapture);
      return true;
    }
    if (element.attachEvent) {
      return element.attachEvent("on" + eventType, eventHandler);
    }
    element["on" + eventType] = eventHandler;
  };

  object.fromQuerystring = function(field, url) {
    var match;
    match = RegExp("^[^#]*[?&]" + field + "=([^&#]*)").exec(url);
    if (!match) {
      return null;
    }
    return decodeURIComponent(match[1].replace(/\+/g, " "));
  };

  capitalizeString = function(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
  };

  ({
    sendRequest: sendRequest,
    toQuery: toQuery,
    fromQuery: fromQuery,
    toNumber: toNumber,
    now: now,
    defineProperty: defineProperty,
    countFrames: countFrames,
    capitalizeString: capitalizeString
  });

}).call(this);
