// Generated by CoffeeScript 1.7.1
(function() {
  window.reqwest || (window.reqwest = require('reqwest'));

  window.JSON || (window.JSON = require('json'));

  module.exports = (function() {
    var capitalizeString, countFrames, defineProperty, fromQuery, getFramePosition, keys, nativeReduce, now, reduce, reduceError, reqwest, sendRequest, toNumber, toQuery;
    reqwest = window.reqwest;
    sendRequest = function(url, options) {
      return reqwest({
        url: url,
        type: 'jsonp',
        success: options.success,
        error: options.error,
        data: options.data
      });
    };
    fromQuery = function(query, delim) {
      var item, key, params, value, _i, _len, _ref, _ref1;
      if (query == null) {
        query = "";
      }
      if (delim == null) {
        delim = "&";
      }
      params = {};
      _ref = query.split(delim);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        _ref1 = item.split("="), key = _ref1[0], value = _ref1[1];
        params[key] = decodeURIComponent(value);
      }
      return params;
    };
    toQuery = function(attributes) {
      return reqwest.toQueryString(attributes);
    };
    toNumber = function(val) {
      return typeof $sf !== "undefined" && $sf !== null ? $sf.lib.lang.cnum(val, 0) : void 0;
    };
    now = function() {
      return (new Date()).getTime();
    };
    defineProperty = function(obj, prop, descriptor) {
      var e;
      try {
        if ("defineProperty" in Object) {
          return Object.defineProperty(obj, prop, descriptor);
        } else if ("__defineGetter__" in obj) {
          if (descriptor.value) {
            obj.__defineGetter__(prop, function() {
              return descriptor.value;
            });
            if (descriptor.writable !== false) {
              return obj.__defineSetter__(prop, function(val) {
                return val[prop] = val;
              });
            }
          } else {
            if (descriptor.get != null) {
              obj.__defineGetter__(prop, descriptor.get);
            }
            if (descriptor.set != null) {
              return obj.__defineSetter__(prop, descriptor.set);
            }
          }
        }
      } catch (_error) {
        e = _error;
        return console.log(e);
      }
    };
    countFrames = function(win) {
      var count, frame, _i, _len, _ref;
      count = win.frames.length;
      _ref = win.frames;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        frame = _ref[_i];
        if (frame !== win) {
          count += countFrames(frame);
        }
      }
      return count;
    };
    getFramePosition = function(win) {
      var count;
      count = 0;
      if (win.parent !== win.top) {
        count = 1 + getFramePosition(win.parent);
      }
      return count;
    };
    nativeReduce = Array.prototype.reduce;
    reduceError = 'Reduce of empty array with no initial value';
    reduce = function(obj, iterator, memo, context) {
      var index, initial, value, _fn, _i, _len;
      initial = arguments.length > 2;
      if (obj == null) {
        obj = [];
      }
      if (nativeReduce && obj.reduce === nativeReduce) {
        if (context) {
          iterator = _.bind(iterator, context);
        }
        return (initial ? obj.reduce(iterator, memo) : obj.reduce(iterator));
      }
      _fn = function(value, index, obj) {
        if (!initial) {
          memo = value;
          initial = true;
        } else {
          memo = iterator.call(context, memo, value, index, obj);
        }
      };
      for (index = _i = 0, _len = obj.length; _i < _len; index = ++_i) {
        value = obj[index];
        _fn(value, index, obj);
      }
      if (!initial) {
        throw new TypeError(reduceError);
      }
      return memo;
    };
    keys = function(obj) {
      return typeof $sf !== "undefined" && $sf !== null ? $sf.lib.lang.keys(obj) : void 0;
    };
    capitalizeString = function(string) {
      return string.charAt(0).toUpperCase() + string.slice(1);
    };
    return {
      sendRequest: sendRequest,
      toQuery: toQuery,
      fromQuery: fromQuery,
      toNumber: toNumber,
      now: now,
      defineProperty: defineProperty,
      countFrames: countFrames,
      capitalizeString: capitalizeString,
      keys: keys,
      getFramePosition: getFramePosition,
      reduce: reduce
    };
  })();

}).call(this);
