// Generated by CoffeeScript 1.7.1
(function() {
  var $sf, AdRequest, advertiser, config, utils;

  $sf = require('../node_modules/safeframe/lib/js/ext/ext')(true);

  utils = require('./shared/utils');

  config = require('./shared/config');

  AdRequest = require('./shared/ad_request');

  advertiser = require('./shared/advertiser');

  (function($sf, window) {
    var Ad, adRequest, findParent, myDepth, onUpdate, parentWindow, referrer, setSessionInfo, _ref;
    Ad = {};
    referrer = document.referrer;
    adRequest = null;
    document.domain = config.domain;
    utils.defineProperty(Ad, "isController", {
      writeable: false,
      value: false,
      configurable: false
    });
    utils.defineProperty(window, "$ad", {
      writeable: false,
      value: Ad,
      configurable: false
    });
    referrer = document.referrer;
    setSessionInfo = function(params) {
      return adRequest.deserialize(params);
    };
    onUpdate = function(status, data) {};
    findParent = function(win, myDepth) {
      if (myDepth == null) {
        myDepth = 0;
      }
      if (win.parent === win.top) {
        try {
          if (win.$ad) {
            return [win, myDepth];
          }
        } catch (_error) {
          return [];
        }
      } else {
        return findParent(win.parent, myDepth + 1);
      }
    };
    $sf.ext.render(true, "");
    $sf.ext.register(0, 0, onUpdate);
    adRequest = new AdRequest($sf.ext.meta("page", "extended"));
    _ref = findParent(window), parentWindow = _ref[0], myDepth = _ref[1];
    adRequest.set({
      depth_position: myDepth
    });
    return advertiser.work(adRequest, parentWindow);
  })($sf, window);

}).call(this);
