// Generated by CoffeeScript 1.7.1
(function() {
  var AdJS, AdRequest, advertiser, config, inPubframe, sf, utils;

  inPubframe = false;

  if (window.parent === window.top && window !== window.top && window["$sf"]) {
    sf = $sf;
    inPubframe = true;
  } else {
    if (!window["$sf"]) {
      sf = require('../node_modules/safeframe/lib/js/host/host')(true);
    }
  }

  AdJS = require('./publisher/slot');

  config = require('./shared/config');

  utils = require('./shared/utils');

  AdRequest = require('./shared/ad_request');

  advertiser = require('./shared/advertiser');

  (function(window) {
    var adframeUrl, initSafeFrame, pageDuration, pageLoadMs, renderAd, sessionObj, sfDom, startTicks;
    sessionObj = new AdRequest();
    startTicks = utils.now();
    pageLoadMs = 0;
    pageDuration = 0;
    adframeUrl = config.ad_url;
    sfDom = $sf.lib.dom;
    sfDom.attach("beforeunload", function() {
      pageDuration = utils.now() - startTicks;
      return true;
    });
    initSafeFrame = function() {
      return $sf.host.Config({
        renderFile: adframeUrl,
        positions: {},
        onStartPosRender: function() {},
        onFailure: function() {},
        onAdLoad: function(id) {
          return AdJS(id).load();
        },
        onBeforePosMsg: function() {},
        onPosMsg: function(id, msg, content) {
          return AdJS(id).handleMessage(msg, content);
        }
      });
    };
    renderAd = function() {
      var div, parent;
      div = document.createElement("div");
      parent = document.createElement("div");
      parent.appendChild(div);
      parent.style.display = "none";
      div.id = sf.lib.lang.guid("creative");
      document.body.appendChild(parent);
      return AdJS("creative").create(div, '', {
        width: 10,
        height: 10,
        renderFile: adframeUrl,
        page: sessionObj.serialize(),
        pageReferrer: document.referrer,
        ignoreEvents: true
      });
    };
    AdJS.render = function(cb) {
      var adJsScript, clientId, s;
      adJsScript = ((function() {
        var _i, _len, _ref, _results;
        _ref = document.getElementsByTagName("script");
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          s = _ref[_i];
          if (sfDom.attr(s, "data-adjs")) {
            _results.push(s);
          }
        }
        return _results;
      })())[0];
      clientId = sfDom.attr(adJsScript, "data-client-id");
      sessionObj.set({
        client_id: clientId
      });
      initSafeFrame();
      return renderAd();
    };
    if (inPubframe) {
      sessionObj.set({
        depth_position: 0
      });
      advertiser.work(sessionObj, window);
    } else {
      (function() {
        return AdJS.render();
      })();
    }
    if (!inPubframe) {
      window.$ad = AdJS;
    }
    return AdJS;
  })(window);

}).call(this);
