// Generated by CoffeeScript 1.7.1
(function() {
  var $sf, Page, config, endpoint, utils;

  $sf = require('../node_modules/safeframe/lib/js/ext/ext')(true);

  utils = require('./shared/utils');

  endpoint = require('./controller/endpoint');

  Page = require('./shared/page');

  config = require('./shared/config');

  (function($sf, window) {
    var Controller, e, onUpdate, page, referrer, requests, setSessionInfo;
    Controller = {};
    referrer = document.referrer;
    page = null;
    requests = {};
    document.domain = config.domain;
    utils.defineProperty(Controller, "isController", {
      writeable: false,
      value: true,
      configurable: false
    });
    utils.defineProperty(Controller, "send", {
      writeable: false,
      value: function(request) {
        requests[request.id] = request;
        request.set(page.attributes, {
          silent: true
        });
        return endpoint.send(request);
      },
      configurable: false
    });
    utils.defineProperty(window, "$ad", {
      writeable: false,
      value: Controller,
      configurable: false
    });
    referrer = document.referrer;
    setSessionInfo = function(params) {
      return page.deserialize(params);
    };
    try {
      utils.defineProperty(document, "referrer", {
        get: function() {
          return "";
        }
      });
    } catch (_error) {
      e = _error;
    }
    onUpdate = function(status, data) {
      switch (status) {
        case "cookie-update":
          return setSessionInfo(unescape(data.value));
      }
    };
    $sf.ext.render(true);
    $sf.ext.register(0, 0, onUpdate);
    page = new Page($sf.ext.meta("page", "extended"));
    page.change(function() {
      return endpoint.send(page);
    });
    return endpoint.send(page, {
      global: true
    }, function() {
      var k, r, _i, _len, _results;
      _results = [];
      for (r = _i = 0, _len = requests.length; _i < _len; r = ++_i) {
        k = requests[r];
        _results.push(r.set(page.attributes, {
          silent: true
        }));
      }
      return _results;
    });
  })($sf, window);

}).call(this);
