// Generated by CoffeeScript 1.7.1
(function() {
  var endpoint, utils;

  utils = require('./shared/utils');

  endpoint = require('./controller/endpoint');

  (function(window) {
    var Controller;
    Controller = {};
    utils.defineProperty(Controller, "isController", {
      writeable: false,
      value: true,
      configurable: false
    });
    utils.defineProperty(Controller, "send", {
      writeable: false,
      value: endpoint.send,
      configurable: false
    });
    return utils.defineProperty(window, "$ad", {
      writeable: false,
      value: Controller,
      configurable: false
    });
  })(window);

}).call(this);
