// Generated by CoffeeScript 1.7.1
(function() {
  var $sf, Session, config, endpoint, utils;

  $sf = require('../node_modules/safeframe/lib/js/ext/ext')(true);

  utils = require('./shared/utils');

  endpoint = require('./controller/endpoint');

  Session = require('./shared/session');

  config = require('./shared/config');

  (function($sf, window) {
    var Controller, e, onUpdate, referrer, session, setSessionInfo;
    Controller = {};
    referrer = document.referrer;
    session = new Session();
    document.domain = config.domain;
    session.change(function() {
      return endpoint.send(session);
    });
    utils.defineProperty(Controller, "isController", {
      writeable: false,
      value: true,
      configurable: false
    });
    utils.defineProperty(Controller, "send", {
      writeable: false,
      value: endpoint.send,
      configurable: false
    });
    utils.defineProperty(window, "$ad", {
      writeable: false,
      value: Controller,
      configurable: false
    });
    referrer = document.referrer;
    setSessionInfo = function(params) {
      return session.set(utils.fromQuery(params));
    };
    try {
      utils.defineProperty(document, "referrer", {
        get: function() {
          return "";
        }
      });
    } catch (_error) {
      e = _error;
    }
    onUpdate = function(status, data) {
      switch (status) {
        case "cookie-update":
          return setSessionInfo(unescape(data.value));
      }
    };
    $sf.ext.render(true);
    setSessionInfo($sf.ext.meta("session", "extended"), {
      silent: true
    });
    return $sf.ext.register(0, 0, onUpdate);
  })($sf, window);

}).call(this);
