// Generated by CoffeeScript 1.7.1
(function() {
  var $sf, Request, config, currentName, events, utils;

  currentName = window.name;

  $sf = require('../node_modules/safeframe/lib/js/ext/ext')(true);

  events = require('./shared/event')(["request", "load", "view", "click", "expanded", "collapsed", "engage", "unview", "unload"]);

  utils = require('./shared/utils');

  Request = require('./request');

  config = require('./shared/config');

  (function($sf, window) {
    var AdJS, VIEWED_STRIKE, attributes, confirmChild, controller, didShow, forceNuke, height, host, isViewedInterval, location, maxViewPercentage, onUpdate, readAd, referrerLevel, registerForEvents, registered, request, requested, sfDom, showAd, showAdTimer, showPage, startTicks, unviewedTicks, updateIsViewed, updateReferrer, viewedPercentages, viewedTicks, width;
    document.domain = config.domain;
    controller = null;
    sfDom = $sf.lib.dom;
    AdJS = {};
    utils.defineProperty(AdJS, "isController", {
      writable: false,
      value: false,
      configurable: false
    });
    request = new Request();
    request.set({
      load_pos: utils.getFramePosition(window),
      v_js: config.version,
      req_url_blind: true,
      tz: (new Date()).getTimezoneOffset()
    });
    utils.findController(function(ctrl) {
      controller = ctrl;
      request.change(function() {
        return controller.send(request);
      });
      return controller.send(request);
    });
    VIEWED_STRIKE = 9;
    viewedTicks = 0;
    unviewedTicks = 0;
    width = window.innerWidth;
    height = window.innerHeight;
    registered = false;
    didShow = false;
    requested = false;
    startTicks = utils.now();
    maxViewPercentage = 0;
    viewedPercentages = [];
    attributes = {};
    AdJS.setDimensions = function(w, h) {
      width = w;
      return height = h;
    };
    registerForEvents = function() {
      registered = true;
      return $sf.ext.register(width, height, onUpdate);
    };
    updateReferrer = function(level) {
      if (level == null) {
        level = "all";
      }
      switch (level) {
        case "all":
          return true;
        case "host":
          utils.defineProperty(document, "referrer", {
            get: function() {
              return "" + document.location.protocol + "//" + host;
            }
          });
          return true;
        case "none":
          return false;
        default:
          return true;
      }
    };
    onUpdate = function(status, data) {
      switch (status) {
        case "expanded":
          return function() {
            return AdJS.expanded();
          };
        case "collapsed":
          return function() {
            return AdJS.collapsed();
          };
        case "geom-update":
          return showAd();
        case "engaged":
          return AdJS.engage();
        case "requested":
          if (!requested) {
            return AdJS.request();
          }
      }
    };
    isViewedInterval = null;
    updateIsViewed = function() {
      var viewPercent, _base;
      viewPercent = (typeof (_base = $sf.ext).inViewPercentage === "function" ? _base.inViewPercentage() : void 0) || 0;
      if (!AdJS.isViewed && viewPercent > 50 && $sf.ext.winHasFocus()) {
        viewedTicks++;
        viewedPercentages.push(viewPercent);
      } else if (AdJS.isViewed && (viewPercent < 50 || !$sf.ext.winHasFocus())) {
        unviewedTicks++;
      } else {
        unviewedTicks = viewedTicks = 0;
        viewedPercentages = [];
      }
      if (viewedTicks === VIEWED_STRIKE) {
        if (!AdJS.isViewed) {
          AdJS.view();
        }
        AdJS.isViewed = true;
      }
      if (unviewedTicks === VIEWED_STRIKE) {
        if (!AdJS.isunViewed) {
          AdJS.unview();
        }
        AdJS.isunViewed = true;
        clearInterval(isViewedInterval);
      }
      if (viewPercent > maxViewPercentage) {
        return maxViewPercentage = viewPercent;
      }
    };
    showAdTimer = null;
    showAd = function(show) {
      var startTime, _base;
      if (((typeof (_base = $sf.ext).inViewPercentage === "function" ? _base.inViewPercentage() : void 0) > 5 && !didShow) || show) {
        if (showAdTimer) {
          clearInterval(showAdTimer);
        }
        startTime = utils.now();
        AdJS.request();
        $sf.ext.showAd(null, function() {
          return AdJS.load();
        });
        return didShow = true;
      } else if (!(showAdTimer || didShow)) {
        return showAdTimer = setInterval(forceNuke, 50);
      }
    };
    forceNuke = function() {
      var _base;
      if ((typeof (_base = $sf.ext).inViewPercentage === "function" ? _base.inViewPercentage() : void 0) > 5 && showAdTimer) {
        clearInterval(showAdTimer);
        showAdTimer = null;
        return $sf.ext.reload();
      }
    };
    $sf.lib.lang.mix(AdJS, events);
    AdJS.on = function(event, cb) {
      return events.on.apply(this, [event, cb]);
    };
    AdJS.expand = function(deltaXorDesc, deltaY, p) {
      return $sf.ext.expand(deltaXorDesc, deltaY, p);
    };
    AdJS.collapse = function() {
      return $sf.ext.collapse();
    };
    AdJS.cookie = function(cookieName, cookieData) {
      return $sf.ext.cookie(coookieName, cookieData);
    };
    AdJS.supports = function(key) {
      return $sf.ext.supports(key);
    };
    AdJS.sendMessage = function(content) {
      return setTimeout(function() {
        return $sf.ext.message(encodeURIComponent(content));
      }, 1);
    };
    sfDom.attach(document.body, "mouseup", function() {
      AdJS.click();
      return true;
    });
    AdJS.click(function() {
      return $sf.ext.click();
    });
    AdJS.view(function() {
      return $sf.ext.viewed();
    });
    AdJS.unview(function() {
      return $sf.ext.unviewed();
    });
    AdJS.load(function() {
      return registerForEvents();
    });
    AdJS.load(function() {
      return isViewedInterval = setInterval(updateIsViewed, 100);
    });
    AdJS.load(function() {
      AdJS.loadChain = utils.countFrames(window);
      return request.set({
        load_chain: AdJS.loadChain
      });
    });
    AdJS.request(function() {
      var geoInfo, _base;
      AdJS.requestTime = utils.now();
      geoInfo = $sf.ext.geom();
      return request.set({
        requested: true,
        requestedAt: utils.now(),
        req_t: utils.now() - startTicks,
        req_view_pct: typeof (_base = $sf.ext).inViewPercentage === "function" ? _base.inViewPercentage() : void 0,
        slot_x: geoInfo.self.l,
        slot_y: geoInfo.self.t,
        slot_w: geoInfo.self.w,
        slot_h: geoInfo.self.h,
        screen_w: window.screen.width,
        screen_h: window.screen.height,
        vp_x: geoInfo.win.l,
        vp_y: geoInfo.win.t,
        vp_w: geoInfo.win.w,
        vp_h: geoInfo.win.h
      });
    });
    AdJS.load(function() {
      AdJS.loadTime = utils.now();
      sfDom.attach(window, "unload", function() {
        return AdJS.unload();
      });
      return request.set({
        loaded: true,
        loadedAt: utils.now(),
        load_t: utils.now() - startTicks
      });
    });
    AdJS.view(function() {
      AdJS.viewTime = utils.now();
      return request.set({
        viewed: true,
        viewedAt: utils.now(),
        view_t: utils.now() - startTicks,
        view_meas: true,
        view_pct: utils.reduce(viewedPercentages, (function(memo, num) {
          return memo + num;
        }), 0) / viewedPercentages.length,
        view_pct_max: maxViewPercentage
      });
    });
    AdJS.engage(function() {
      AdJS.engageTime = utils.now();
      return request.set({
        engaged: true,
        view_eng: true,
        engagedAt: utils.now()
      });
    });
    AdJS.click(function() {
      AdJS.clickTime = utils.now();
      return request.set({
        clicked: true,
        clickedAt: utils.now(),
        clk_t: utils.now() - startTicks
      });
    });
    AdJS.unview(function() {
      AdJS.unviewTime = utils.now();
      return request.set({
        unviewed: true,
        unviewedAt: utils.now(),
        view_dur: utils.now() - AdJS.viewedAt,
        view_pct_max: maxViewPercentage
      });
    });
    AdJS.unload(function() {
      AdJS.unloadTime = utils.now();
      return request.set({
        unloaded: true,
        unloadedAt: utils.now(),
        unl_t: utils.now() - startTicks
      });
    });
    $sf.ext.render(false);
    didShow = !$sf.lib.lang.cbool($sf.ext.meta("inview", "extended"));
    referrerLevel = $sf.ext.meta("referrer", "extended") || "all";
    host = $sf.ext.meta("host", "extended");
    $sf.ext.deleteMeta("host", "extended");
    location = $sf.ext.meta("location", "extended");
    $sf.ext.deleteMeta("location", "extended");
    AdJS.slotId = $sf.ext.meta("slot_id", "extended");
    AdJS.count = $sf.ext.meta("load_n", "extended");
    request.set({
      slot_id: $sf.ext.meta("slot_id", "extended"),
      load_n: $sf.ext.meta("load_n", "extended"),
      page_url: location,
      page_host: host
    }, {
      silent: true
    });
    showPage = document.location.href === document.referrer || updateReferrer(referrerLevel);
    if (showPage) {
      showAd(didShow);
    } else {
      window.name = currentName;
      document.location = document.location;
    }
    confirmChild = function(win, adFrame) {
      var childFrame;
      if (win === adFrame) {
        return true;
      }
      return ((function() {
        var _i, _len, _ref, _results;
        _ref = win.frames;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          childFrame = _ref[_i];
          if (confirmChild(childFrame, adFrame)) {
            _results.push(childFrame);
          }
        }
        return _results;
      })()).length > 0;
    };
    readAd = function(adFrame) {
      if (confirmChild(window, adFrame)) {
        return controller.combine(request, adFrame.getDetails());
      }
    };
    utils.defineProperty(window, "$ad", {
      writable: false,
      value: AdJS,
      configurable: false
    });
    utils.defineProperty(AdJS, "readAd", {
      writable: false,
      value: readAd,
      configurable: false
    });
    return AdJS;
  })($sf, window);

}).call(this);
