// Generated by CoffeeScript 1.7.1
(function() {
  var AdJS, Session, config, engagement, sf, stream, utils;

  sf = require('safeframe');

  engagement = require('./shared/engagement');

  Session = require('./shared/session');

  AdJS = require('./publisher/slot');

  stream = require('./shared/stream');

  config = require('./shared/config');

  utils = require('./shared/utils');

  (function(window) {
    var controllerUrl, doRender, globalConfig, initSafeFrame, pageDuration, pageLoadMs, renderController, safeframeUrl, session, sfDom, startTicks;
    session = new Session();
    session.incr("p");
    startTicks = utils.now();
    pageLoadMs = 0;
    pageDuration = 0;
    safeframeUrl = config.cdn_url;
    controllerUrl = config.controller_url;
    sfDom = $sf.lib.dom;
    sfDom.attach("beforeunload", function() {
      pageDuration = utils.now() - startTicks;
      return true;
    });
    globalConfig = {
      keys: [],
      safeframe_url: safeframeUrl
    };
    doRender = function(cb) {
      var d, div, divs, sfPositions, _i, _len;
      sfPositions = {};
      if (!sfDom.ready()) {
        sfDom.wait(function() {
          var args;
          pageLoadMs = utils.now() - startTicks;
          doRender.apply(null, args);
          return args = null;
        });
      } else {
        renderController();
        divs = (function() {
          var _i, _len, _ref, _results;
          _ref = document.getElementsByTagName("div");
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            div = _ref[_i];
            _results.push(div);
          }
          return _results;
        })();
        for (_i = 0, _len = divs.length; _i < _len; _i++) {
          d = divs[_i];
          if (sfDom.attr(d, "data-adjs")) {
            (function(d) {
              return AdJS.create(d, session);
            })(d);
          }
        }
        return typeof cb === "function" ? cb() : void 0;
      }
    };
    initSafeFrame = function() {
      return $sf.host.Config({
        renderFile: globalConfig.safeframe_url,
        positions: {},
        onStartPosRender: function() {},
        onFailure: function() {},
        onAdLoad: function(id) {
          return AdJS(id).load();
        },
        onBeforePosMsg: function() {},
        onPosMsg: function(id, msg, content) {
          return AdJS(id).handleMessage(msg, content);
        }
      });
    };
    AdJS.view(function() {
      return session.incr("av");
    });
    AdJS.engage(function() {
      return session.incr("ae");
    });
    AdJS.load(function() {
      return session.incr("a");
    });
    AdJS.click(function() {
      return session.incr("ac");
    });
    AdJS.load(function() {
      return console.log("loaded");
    });
    session.change(function() {
      var ad, _, _ref, _results;
      _ref = AdJS.slots;
      _results = [];
      for (_ in _ref) {
        ad = _ref[_];
        _results.push(ad.notifyFrame("cookie-update", session.serializeCookie()));
      }
      return _results;
    });
    renderController = function() {
      var div;
      div = document.createElement("div");
      div.style.display = "none";
      div.id = sf.lib.lang.guid("controller");
      document.body.appendChild(div);
      return AdJS("controller").create(div, "", {
        width: 1,
        height: 1,
        supports: ["write-cookie", "read-cookie"],
        renderFile: controllerUrl,
        session: session != null ? session.serializeCookie() : void 0,
        pageReferrer: document.referrer,
        ignoreEvents: true
      });
    };
    AdJS.render = function(cb) {
      var adJsScript, clientId, s;
      adJsScript = ((function() {
        var _i, _len, _ref, _results;
        _ref = document.getElementsByTagName("script");
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          s = _ref[_i];
          if (sfDom.attr(s, "data-adjs")) {
            _results.push(s);
          }
        }
        return _results;
      })())[0];
      clientId = sfDom.attr(adJsScript, "data-client-id");
      session.set("client_id", clientId);
      initSafeFrame();
      return doRender();
    };
    engagement.onEngagement(function() {
      var ad, _, _ref, _results;
      _ref = AdJS.slots;
      _results = [];
      for (_ in _ref) {
        ad = _ref[_];
        if (ad.currentlyInview() && !ad.engaged) {
          _results.push(ad.engage());
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    });
    (function() {
      return AdJS.render();
    })();
    AdJS.session = session;
    window.$ad = AdJS;
    return AdJS;
  })(window);

}).call(this);
