// Generated by CoffeeScript 1.7.1
(function() {
  var AdJS, Session, config, engagement, sf, stream;

  sf = require('safeframe');

  engagement = require('./shared/engagement');

  Session = require('./shared/session');

  AdJS = require('./publisher/slot');

  stream = require('./shared/stream');

  config = require('./shared/config');

  (function(window) {
    var doRender, globalConfig, initSafeFrame, safeframeUrl, session, sfDom;
    session = new Session();
    stream.page(session);
    safeframeUrl = config.cdn_url;
    sfDom = $sf.lib.dom;
    globalConfig = {
      keys: [],
      safeframe_url: safeframeUrl
    };
    doRender = function() {
      var d, div, divs, sfPositions, _i, _len, _results;
      sfPositions = {};
      if (!sfDom.ready()) {
        sfDom.wait(function() {
          var args;
          doRender.apply(null, args);
          return args = null;
        });
      } else {
        divs = (function() {
          var _i, _len, _ref, _results;
          _ref = document.getElementsByTagName("div");
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            div = _ref[_i];
            _results.push(div);
          }
          return _results;
        })();
        _results = [];
        for (_i = 0, _len = divs.length; _i < _len; _i++) {
          d = divs[_i];
          if (sfDom.attr(d, "data-adjs")) {
            _results.push((function(d) {
              return AdJS.create(d, session);
            })(d));
          }
        }
        return _results;
      }
    };
    initSafeFrame = function() {
      return $sf.host.Config({
        renderFile: globalConfig.safeframe_url,
        positions: {},
        onStartPosRender: function() {},
        onFailure: function() {},
        onAdLoad: function(id) {
          return AdJS(id).load();
        },
        onBeforePosMsg: function() {},
        onPosMsg: function(id, msg, content) {
          return AdJS(id).handleMessage(msg, content);
        }
      });
    };
    AdJS.view(function() {
      return session.incr("av");
    });
    AdJS.engage(function() {
      return session.incr("ae");
    });
    AdJS.load(function() {
      return session.incr("a");
    });
    AdJS.click(function() {
      return session.incr("ac");
    });
    AdJS.load(function() {
      return console.log("loaded");
    });
    session.change(function() {
      var ad, _, _ref, _results;
      console.log("wtf");
      _ref = AdJS.slots;
      _results = [];
      for (_ in _ref) {
        ad = _ref[_];
        _results.push(ad.notifyFrame("cookie-update", session.serializeCookie()));
      }
      return _results;
    });
    AdJS.render = function() {
      var adJsScript, s;
      adJsScript = ((function() {
        var _i, _len, _ref, _results;
        _ref = document.getElementsByTagName("script");
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          s = _ref[_i];
          if (sfDom.attr(s, "data-adjs")) {
            _results.push(s);
          }
        }
        return _results;
      })())[0];
      initSafeFrame();
      return doRender();
    };
    engagement.onEngagement(function() {
      var ad, _, _ref, _results;
      _ref = AdJS.slots;
      _results = [];
      for (_ in _ref) {
        ad = _ref[_];
        if (ad.currentlyInview() && !ad.engaged) {
          _results.push(ad.engage());
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    });
    (function() {
      return AdJS.render();
    })();
    AdJS.session = session;
    window.$ad = AdJS;
    return AdJS;
  })(window);

}).call(this);
