// Generated by CoffeeScript 1.7.1
(function() {
  var AdJS, AdRequest, Page, config, engagement, sf, utils;

  if (!window["$sf"]) {
    sf = require('safeframe');
  }

  engagement = require('./shared/engagement');

  Page = require('./shared/page');

  AdJS = require('./publisher/slot');

  config = require('./shared/config');

  utils = require('./shared/utils');

  AdRequest = require('./shared/ad_request');

  (function(window) {
    var controllerUrl, doRender, initSafeFrame, pageDuration, pageLoadMs, renderController, safeframeUrl, sessionObj, sfDom, startTicks;
    sessionObj = new Page();
    startTicks = utils.now();
    pageLoadMs = 0;
    pageDuration = 0;
    safeframeUrl = config.cdn_url;
    controllerUrl = config.controller_url;
    sfDom = $sf.lib.dom;
    sfDom.attach("beforeunload", function() {
      pageDuration = utils.now() - startTicks;
      return true;
    });
    doRender = function(cb) {
      var d, div, divs, sfPositions, _i, _len;
      sfPositions = {};
      if (!sfDom.ready()) {
        sfDom.wait(function() {
          var args;
          pageLoadMs = utils.now() - startTicks;
          doRender.apply(null, args);
          return args = null;
        });
      } else {
        renderController();
        divs = (function() {
          var _i, _len, _ref, _results;
          _ref = document.getElementsByTagName("div");
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            div = _ref[_i];
            _results.push(div);
          }
          return _results;
        })();
        for (_i = 0, _len = divs.length; _i < _len; _i++) {
          d = divs[_i];
          if (sfDom.attr(d, "data-adjs")) {
            (function(d) {
              return AdJS.create(d, sessionObj);
            })(d);
          }
        }
        return typeof cb === "function" ? cb() : void 0;
      }
    };
    initSafeFrame = function() {
      return $sf.host.Config({
        renderFile: window === window.top ? safeframeUrl : adframeUrl,
        positions: {},
        onStartPosRender: function() {},
        onFailure: function() {},
        onAdLoad: function(id) {
          return AdJS(id).load();
        },
        onBeforePosMsg: function() {},
        onPosMsg: function(id, msg, content) {
          return AdJS(id).handleMessage(msg, content);
        }
      });
    };
    renderController = function() {
      var div, parent;
      div = document.createElement("div");
      parent = document.createElement("div");
      parent.appendChild(div);
      parent.style.display = "none";
      div.id = sf.lib.lang.guid("controller");
      document.body.appendChild(parent);
      return AdJS("controller").create(div, '', {
        width: 10,
        height: 10,
        supports: ["write-cookie", "read-cookie"],
        renderFile: controllerUrl,
        page: sessionObj.serializedAttributes(),
        pageReferrer: document.referrer,
        ignoreEvents: true
      });
    };
    AdJS.render = function(cb) {
      var adJsScript, clientId, s;
      adJsScript = ((function() {
        var _i, _len, _ref, _results;
        _ref = document.getElementsByTagName("script");
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          s = _ref[_i];
          if (sfDom.attr(s, "data-adjs")) {
            _results.push(s);
          }
        }
        return _results;
      })())[0];
      clientId = sfDom.attr(adJsScript, "data-client-id");
      sessionObj.set({
        client_id: clientId
      });
      initSafeFrame();
      return doRender(cb);
    };
    engagement.onEngagement(function() {
      var ad, _, _ref, _results;
      _ref = AdJS.slots;
      _results = [];
      for (_ in _ref) {
        ad = _ref[_];
        if (ad.currentlyInview() && !ad.engaged) {
          _results.push(ad.engage());
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    });
    (function() {
      return AdJS.render();
    })();
    window.$ad = AdJS;
    return AdJS;
  })(window);

}).call(this);
