// Generated by CoffeeScript 1.7.1
(function() {
  var Base,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require('./shared/base');

  module.exports = (function(window) {
    var Request;
    Request = (function(_super) {
      __extends(Request, _super);

      function Request() {
        Request.__super__.constructor.apply(this, arguments);
      }

      Request.prototype.path = "/event";

      Request.prototype.constantFields = ["site_user_id", "page_id", "visit_id", "url", "req_id"];

      return Request;

    })(Base);
    return Request;
  })(window);

}).call(this);
