// Generated by CoffeeScript 1.7.1
(function() {
  var Base, uuid,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require('./shared/base');

  uuid = require('node-uuid');

  module.exports = (function(window) {
    var Request;
    Request = (function(_super) {
      var REQ_INTERVAL;

      __extends(Request, _super);

      REQ_INTERVAL = 50;

      Request.prototype.path = "/event";

      function Request(clientId, sessionId) {
        this.clientId = clientId;
        this.sessionId = sessionId;
        Request.__super__.constructor.apply(this, arguments);
        this.id = uuid.v4();
      }

      return Request;

    })(Base);
    return Request;
  })(window);

}).call(this);
