// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = (function($sf, window) {
    var canCors, corsRequest, jsonpRequest, objToQs, sendRequest;
    window.JSON || (window.JSON = require('json'));
    canCors = (typeof XMLHttpRequest !== "undefined" && XMLHttpRequest !== null) && 'withCredentials' in new XMLHttpRequest();
    sendRequest = function(url, params, cb) {
      if (canCors) {
        return corsRequest(url, params, cb);
      } else {
        return jsonpRequest(url, params, cb);
      }
    };
    jsonpRequest = function(url, params, cb) {
      var cbName, cleanup, script, src;
      cleanup = function() {
        if (script.parentNode) {
          script.parentNode.removeChild(script);
        }
        if (cbName in window) {
          delete window[cbName];
        }
      };
      cbName = $sf.lib.lang.guid("adjs_cb");
      src = Sunblock.buildJsonpRequest(url, params, cbName);
      script = document.createElement("script");
      script.src = src;
      script.async = true;
      script.className = "adjs-jsonp";
      script.onerror = function() {
        return cleanup();
      };
      window[cbName] = function() {
        cleanup();
        callback.apply(null, arguments_);
      };
      return Sunblock.documentAlias.getElementsByTagName("script")[0].parentNode.appendChild(script);
    };
    corsRequest = function(url, params, cb) {};
    return objToQs = function(obj) {};
  })($sf, window);

}).call(this);
